//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.12.01 at 11:34:14 AM CST
//

package com.lujunyu.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p><basic> &lt;complexType> &lt;complexContent> &lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element name="req"
 * type="{http://www.w3.org/2001/XMLSchema}string"/> &lt;element name="resp"
 * type="{http://www.w3.org/2001/XMLSchema}string"/> &lt;/sequence> &lt;attGroup
 * ref="{http://www.w3school.com.cn}commonAttr"/> &lt;/restriction> &lt;/complexContent>
 * &lt;/complexType> </basic>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"req", "resp"})
@XmlRootElement(name = "channel")
public class Channel {

  @XmlElement(required = true)
  protected String req;

  @XmlElement(required = true)
  protected String resp;

  @XmlAttribute(name = "id")
  protected String id;

  @XmlAttribute(name = "protocol")
  protected String protocol;

  @XmlAttribute(name = "sync")
  protected Boolean sync;

  /**
   * Gets the value of the req property.
   *
   * @return possible object is {@link String }
   */
  public String getReq() {
    return req;
  }

  /**
   * Sets the value of the req property.
   *
   * @param value allowed object is {@link String }
   */
  public void setReq(String value) {
    this.req = value;
  }

  /**
   * Gets the value of the resp property.
   *
   * @return possible object is {@link String }
   */
  public String getResp() {
    return resp;
  }

  /**
   * Sets the value of the resp property.
   *
   * @param value allowed object is {@link String }
   */
  public void setResp(String value) {
    this.resp = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the protocol property.
   *
   * @return possible object is {@link String }
   */
  public String getProtocol() {
    return protocol;
  }

  /**
   * Sets the value of the protocol property.
   *
   * @param value allowed object is {@link String }
   */
  public void setProtocol(String value) {
    this.protocol = value;
  }

  /**
   * Gets the value of the sync property.
   *
   * @return possible object is {@link Boolean }
   */
  public boolean isSync() {
    if (sync == null) {
      return false;
    } else {
      return sync;
    }
  }

  /**
   * Sets the value of the sync property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setSync(Boolean value) {
    this.sync = value;
  }

  @Override
  public String toString() {
    return "Channel [req="
        + req
        + ", resp="
        + resp
        + ", id="
        + id
        + ", protocol="
        + protocol
        + ", sync="
        + sync
        + ", getReq()="
        + getReq()
        + ", getResp()="
        + getResp()
        + ", getId()="
        + getId()
        + ", getProtocol()="
        + getProtocol()
        + ", isSync()="
        + isSync()
        + ", getClass()="
        + getClass()
        + ", hashCode()="
        + hashCode()
        + ", toString()="
        + super.toString()
        + "]";
  }
}
