//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.12.01 at 11:34:14 AM CST
//

package com.lujunyu.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p><basic> &lt;complexType> &lt;complexContent> &lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}anyType"> &lt;sequence> &lt;element
 * ref="{http://www.w3school.com.cn}channel"/> &lt;/sequence> &lt;/restriction> &lt;/complexContent>
 * &lt;/complexType> </basic>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"channel"})
@XmlRootElement(name = "root")
public class Root {

  @XmlElement(namespace = "http://www.w3school.com.cn", required = true)
  protected Channel channel;

  /**
   * Gets the value of the channel property.
   *
   * @return possible object is {@link Channel }
   */
  public Channel getChannel() {
    return channel;
  }

  /**
   * Sets the value of the channel property.
   *
   * @param value allowed object is {@link Channel }
   */
  public void setChannel(Channel value) {
    this.channel = value;
  }

  @Override
  public String toString() {
    return "Root [channel="
        + channel
        + ", getChannel()="
        + getChannel()
        + ", getClass()="
        + getClass()
        + ", hashCode()="
        + hashCode()
        + ", toString()="
        + super.toString()
        + "]";
  }
}
